### ISSUE TITLE
Create SignIn and SignUp Page

### ISSUE THREAD

**Issue by SubbU22399** [SubbU22399/buddy#1]
1.create a signIn ad SignUp

**Comment by SubbU22399** [comment]
have initilazed the app and started coding for the signIn Page.

**Comment by SubbU22399** [comment]
The creating on the login page is "Sucess"
If we need any changes in UI we can do it later no 

![Image](https://github.com/user-attachments/assets/0b2b49e1-506c-43dc-b7d4-be3bc0f654cb)
![Image](https://github.com/user-attachments/assets/c596e1b4-a10d-48b9-99c3-51f3a125179c)

**Comment by SubbU22399** [comment]
@preeti22399 please review this please and mark it as done.

**Comment by preeti22399** [comment]
Reviewed
